# Generated by Django 4.2.10 on 2024-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_auto_20200813_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdonor",
            name="doctorprescription",
            field=models.CharField(default=12, max_length=300),
            preserve_default=False,
        ),
    ]
